# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-23 08:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trans_date', models.DateTimeField(auto_now=True)),
                ('trans_type', models.CharField(choices=[('offer', 'OFFER'), ('cancel', 'CANCEL OFFER'), ('close', 'CLOSE')], max_length=64)),
                ('prop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='properties.Property')),
            ],
        ),
    ]
